BACKLIGHT_ENABLE  = no
BOOTMAGIC_ENABLE  = no
COMMAND_ENABLE    = yes
CONSOLE_ENABLE    = yes
EXTRAKEY_ENABLE   = yes
MOUSEKEY_ENABLE   = yes
NKRO_ENABLE       = yes
VISUALIZER_ENABLE = no

EXTRAFLAGS += -flto
